/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HardwareSetupRouteImport } from './routes/hardware-setup'
import { Route as IndexRouteImport } from './routes/index'

const HardwareSetupRoute = HardwareSetupRouteImport.update({
  id: '/hardware-setup',
  path: '/hardware-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hardware-setup': typeof HardwareSetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hardware-setup': typeof HardwareSetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hardware-setup': typeof HardwareSetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hardware-setup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hardware-setup'
  id: '__root__' | '/' | '/hardware-setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HardwareSetupRoute: typeof HardwareSetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/hardware-setup': {
      id: '/hardware-setup'
      path: '/hardware-setup'
      fullPath: '/hardware-setup'
      preLoaderRoute: typeof HardwareSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HardwareSetupRoute: HardwareSetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
